#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.10.131:3306/mymall_sms?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      serverAddr: 127.0.0.1:8848
##      username: 'nacos'
##      password: 'nacos'
#      config:
#        namespace: coupon
#        group: dev
#      discovery:
#        server-addr: 127.0.0.1:8848
#  config:
#    import:
#      - nacos:mymall-coupon.properties?refreshEnabled=true
#  application:
#    name: myMall-coupon
#
#
#server:
#  port: 7000
#
#
#
