spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://myMall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://myMall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://myMall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://myMall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://myMall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: thirdParty_route
          uri: lb://myMall-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://myMall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mymall_search_route
          uri: lb://myMall-search
          predicates:
            - Host=search.mymall.com

        - id: mymall_host_route
          uri: lb://myMall-product
          predicates:
            - Host=**.mymall.com, mymall.com





