spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000  # 10秒的连接超时
        response-timeout: 5000  # 响应超时设置
        pool:
          max-connections: 1000  # 增加最大连接数
          acquire-timeout: 60000  # 获取连接超时时间

      routes:
        - id: product_route
          uri: lb://myMall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://myMall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://myMall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://myMall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://myMall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: thirdParty_route
          uri: lb://myMall-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://myMall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mymall_search_route
          uri: lb://myMall-search
          predicates:
            - Host=search.mymall.com

        - id: mymall_auth_route
          uri: lb://myMall-auth-server
          predicates:
            - Host=auth.mymall.com

        - id: mymall_cart_route
          uri: lb://myMall-ware
          predicates:
            - Host=cart.mymall.com

        - id: mymall_order_route
          uri: lb://myMall-order
          predicates:
            - Host=order.mymall.com

        - id: mymall_host_route
          uri: lb://myMall-product
          predicates:
            - Host=item.mymall.com, mymall.com





