spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.131:3306/mymall_wms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      #      username: 'nacos'
      #      password: 'nacos'
      config:
        namespace: ware
        group: dev
      discovery:
        server-addr: 127.0.0.1:8848

  config:
    import:
      - nacos:mymall-ware.properties?refreshEnabled=true
  application:
    name: myMall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.10.131
    port: 6379
    password: 123456
  session:
    store-type: redis
    redis:
      flush-mode: on_save
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 11000

logging:
  level:
    com.example: debug

mymall:
  thread:
    core-pool-size: 20
    max-pool-size: 200
    keep-alive-time: 10






